input_csv: input/multimers.csv
templates_to_exclude: templates_to_exclude.txt
container: ../../singularity_containers/colabfold/colabfold_1.5.9-cuda12.2.2_parallel_fix_2bec5c7_relax_rsync_merged_to_latest.sif
output_dir: output
